collect_jobs:
    description: >
      Collect freelance job postings from web platforms.
    expected_output: >
      A list of collected job postings.
    agent: researcher

generate_report:
    description: >
      Generate a summary report of job opportunities.
    expected_output: >
      A markdown report summarizing job opportunities.
    agent: reporting_analyst
