search_jobs:
    description: >
      Search and collect job postings from the primary job platform,
      focusing on {topic} positions. Gather essential information
      including job title, description, requirements, and application details.
    expected_output: >
      A list of relevant job postings with complete information.
    agent: job_searcher

process_data:
    description: >
      Clean and standardize the collected job posting data. Ensure
      consistent formatting, remove duplicates, and validate essential
      fields for {topic} positions.
    expected_output: >
      A structured dataset of processed job postings ready for analysis.
    agent: data_processor
